DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/AditionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class AditionalController : Controller
    {
        // GET: Aditional
        public ActionResult Index()
        {
            return View();
        }

        // GET: Aditional/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Aditional/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aditional/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Aditional/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Aditional/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Aditional/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Aditional/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/ClausedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class ClausedController : Controller
    {
        // GET: Calused
        public ActionResult Index()
        {
            return View();
        }

        // GET: Calused/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calused/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calused/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calused/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calused/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calused/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calused/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Document
        public ActionResult Index()
        {
            return View();
        }

        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Document/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Document/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Document/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Document/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Views/Claused/Index.cshtml
@{
    ViewData["Title"] = "Claused";
    ViewData["Step"] = "6";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- @await Html.PartialAsync("_JumboBrand") -->
@await Html.PartialAsync("_StepWizard")
<h2> Spacial Claused & Exclusion / เงื่อนไขพิเศษและข้อยกเว้นสำคัญ</h2>
<div class="row top-buffer">
    <div class="col-md-12">
        <hr />
        <div class="col-md-12 card card-3">
            <div id="spacial-pd" class="top-buffer">
                <button type="button" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                <b> Spacial Claused PD </b>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="" class="list-group-item">
                        Cras justo odio
                    </a>
                    <a href="" class="list-group-item">Dapibus ac facilisis in</a>
                    <a href="" class="list-group-item">Morbi leo risus</a>
                    <a href="" class="list-group-item">Porta ac consectetur ac</a>
                    <a href="" class="list-group-item">Vestibulum at eros</a>
                </div>
            </div>

            <div id="spacial-bi">
                <button type="button" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                <b> Sapacial Claused BI </b>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="" class="list-group-item">
                        Cras justo odio
                    </a>
                    <a href="" class="list-group-item">Dapibus ac facilisis in</a>
                    <a href="" class="list-group-item">Morbi leo risus</a>
                    <a href="" class="list-group-item">Porta ac consectetur ac</a>
                    <a href="" class="list-group-item">Vestibulum at eros</a>
                </div>
            </div>

            <div id="attachment-list">
                <button type="button" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                <b> Attchtment list </b>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="" class="list-group-item">Attchtment list</a>
                    <a href="" class="list-group-item">Dapibus ac facilisis in</a>
                    <a href="" class="list-group-item">Morbi leo risus</a>
                    <a href="" class="list-group-item">Porta ac consectetur ac</a>
                    <a href="" class="list-group-item">Vestibulum at eros</a>
                </div>
            </div>

            <div>
                <div >
                    <a asp-controller="Aditional" asp-action="Index" class="btn btn-danger">Save Back</a>
                    <a asp-controller="Document" asp-action="Index" class="btn btn-primary">Save next</a>
                </div>
            </div>
        </div>
    </div>
</div>