DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/AditionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class AditionalController : Controller
    {
        // GET: Aditional
        public ActionResult Index()
        {
            return View();
        }

        // GET: Aditional/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Aditional/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aditional/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Aditional/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Aditional/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Aditional/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Aditional/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/ClausedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class ClausedController : Controller
    {
        // GET: Calused
        public ActionResult Index()
        {
            return View();
        }

        // GET: Calused/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calused/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calused/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calused/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calused/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calused/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calused/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/CoverageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class CoverageController : Controller
    {
        // GET: Coverage
        public ActionResult Index()
        {
            return View();
        }

        // GET: Coverage/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Coverage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coverage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Coverage/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Coverage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Coverage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Coverage/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Views/Aditional/Index.cshtml
@{
    ViewData["Title"] = "Aditionnal";
    ViewData["Step"] = "5";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Html.PartialAsync("_StepWizard")
    <h2>Addition Peril</h2>
    <div class="row top-buffer">
        <div class="col-md-12">
            <hr />
            <div class="col-md-12 card card-3">
                <div id="locationPeril" class="panel-body">
                    <div class="form-group">
                        <button id="addProperty" type="button" class="btn btn-success" aria-label="Left Align">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Peril
                        </button>
                    </div>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td class="">รหัส</td>
                                <td class="">รายละเอียด</td>
                                <td class="">Min</td>
                                <td class="">Max</td>
                                <td class="">Rate</td>
                                <td class="">ทุุนประกัน</td>
                                <td class="">เบี้ยประกัน</td>
                                <td class="">หมายเหตุ</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>123456789</td>
                                <td>ความคุมครองความเสียหายจากน้ำท่วม</td>
                                <td>50000</td>
                                <td>100000</td>
                                <td>100</td>
                                <td>1,000,000</td>
                                <td>50000</td>
                                <td>??????????</td>
                            </tr>
                            <tr>
                                <td>123456789</td>
                                <td>ความคุมครองความเสียหายจากน้ำท่วม</td>
                                <td>50000</td>
                                <td>100000</td>
                                <td>100</td>
                                <td>1,000,000</td>
                                <td>50000</td>
                                <td>??????????</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div>
                    <div class="">
                        <a asp-controller="Coverage" asp-action="Index" class="btn btn-danger">Save Back</a>
                        <a asp-controller="Claused" asp-action="Index" class="btn btn-primary">Save next</a>
                    </div>
                </div>
            </div>
        </div>
    </div>