DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Category/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/CoverageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class CoverageController : Controller
    {
        // GET: Coverage
        public ActionResult Index()
        {
            return View();
        }

        // GET: Coverage/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Coverage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coverage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Coverage/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Coverage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Coverage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Coverage/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/LocationAssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class LocationAssetController : Controller
    {
        // GET: LocationAsset
        public ActionResult Index()
        {
            return View();
        }

        // GET: LocationAsset/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LocationAsset/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocationAsset/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAsset/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LocationAsset/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAsset/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LocationAsset/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class LocationController : Controller
    {
        // GET: Location
        public ActionResult Index()
        {
            return View();
        }

        // GET: Location/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Location/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Location/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Location/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Location/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Location/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Location/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Views/Location/Index.cshtml
@{
    ViewData["Title"] = "Location";
    ViewData["Step"] = "3";
}

<!-- @await Html.PartialAsync("_JumboBrand") -->
@await Html.PartialAsync("_StepWizard")
    <h2> Location ( ระบุสถานที่เอาประกันภัย ) </h2>
    <div class="row top-buffer">
        <div class="col-md-12">
            <hr />
            <div class="col-md-12 card card-3">
                <div>
                    <a asp-controller="LocationAsset" asp-action="Index" class="btn btn-success" aria-label="Left Align">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Add Location
                    </a>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td class="">สถานที่ตั้งทรัพย์สิน</td>
                                <td class="">สถานที่ใช้เป็น</td>
                                <td class="">ทุนประกันรวม</td>
                                <td class="">Type of Owner</td>
                                <td class="">ลักษณะทรัพย์สิน</td>
                                <td class="">สัดส่วน %</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>404 The Prima พหลโยธิน</td>
                                <td>???</td>
                                <td>1,000,000</td>
                                <td>Owner</td>
                                <td>บ้านเดี่ยว</td>
                                <td>50 %</td>
                            </tr>
                            <tr>
                                <td>404 The Prima พหลโยธิน</td>
                                <td>???</td>
                                <td>1,000,000</td>
                                <td>Owner</td>
                                <td>บ้านเดี่ยว</td>
                                <td>50 %</td>
                            </tr>
                            <tr>
                                <td>404 The Prima พหลโยธิน</td>
                                <td>???</td>
                                <td>1,000,000</td>
                                <td>Owner</td>
                                <td>บ้านเดี่ยว</td>
                                <td>50 %</td>
                            </tr>
                        </tbody>
                    </table>
                    <div>
                        <a asp-controller="Category" asp-action="Index" class="btn btn-danger">Save Back</a>
                        <a asp-controller="Coverage" asp-action="Index" class="btn btn-primary">Save next</a>
                    </div>
                </div>
            </div>
        </div>
    </div>