DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/BuildingDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class BuildingDetailController : Controller
    {
        // GET: BuildingDetail
        public ActionResult Index()
        {
            return View();
        }

        // GET: BuildingDetail/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BuildingDetail/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BuildingDetail/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BuildingDetail/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BuildingDetail/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BuildingDetail/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BuildingDetail/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/LocationAssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class LocationAssetController : Controller
    {
        // GET: LocationAsset
        public ActionResult Index()
        {
            return View();
        }

        // GET: LocationAsset/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LocationAsset/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocationAsset/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAsset/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LocationAsset/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAsset/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LocationAsset/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Controllers/PropertyEnsuredController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DNSSoft.Chubb.QuatationTools.Controllers
{
    public class PropertyEnsuredController : Controller
    {
        // GET: PropertyEnsured
        public ActionResult Index()
        {
            return View();
        }

        // GET: PropertyEnsured/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PropertyEnsured/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PropertyEnsured/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PropertyEnsured/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PropertyEnsured/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PropertyEnsured/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PropertyEnsured/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Views/BuildingDetail/Index.cshtml
@{
    ViewData["Title"] = "Buiding Details";
    ViewData["Step"] = "3";
}

@await Html.PartialAsync("_StepWizard")
@await Html.PartialAsync("_riskModal")

    <h2> รายละเอียดเกี่ยวกับสิ่งก่อสร้าง </h2>
    <div class="row top-buffer">
        <div class="col-md-12">
            <hr />
            <div class="col-md-12 card card-3">
                <form>
                    <div class="">
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="businessType">Type of ownfer</label>
                            <select id="businessType" class="form-control">
                                <option value="owner">Owner</option>
                                <option value="tenant">Tenant</option>
                            </select>
                        </div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="businessType">ลักษณะทรัพย์สิน</label>
                            <select id="businessType" class="form-control">
                                <option value="owner">Owner</option>
                                <option value="tenant">Tenant</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="package">ชั้นที่</label>
                            <input type="text" class="form-control" />
                        </div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="businessType">ลักษณะสิ่งก่อสร้าง</label>
                            <select id="businessType" class="form-control">
                                <option value="owner">Owner</option>
                                <option value="tenant">Tenant</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="package">สถานที่ใช้เป็น</label>
                            <input type="text" class="form-control" />
                        </div>
                        <div id="risk-code" class="form-group col-xs-10 col-md-4">                            
                            <label for="package">รหัสภัย</label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Risk code...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" data-toggle="modal" data-target="#riskSearchModal">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                            <!-- <input type="text" class="form-control" /> -->
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="package">ชั้นของสิ่งปลูกสร้าง</label>
                            <input type="text" class="form-control" />
                        </div>
                        <div class="form-group col-xs-10 col-md-4">
                            <label for="package">สัดส่วนที่บริษัทรับความเสี่ยง</label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="0-100" value="100">
                                <span class="input-group-addon" id="basic-addon1">%</span>
                            </div>
                             <small class="help-block">0 - 100</small>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-xs-10 col-md-4">
                            <div>
                                <a asp-controller="PropertyEnsured" asp-action="Index" class="btn btn-primary">Save Continue</a>
                            </div>
                            <div>
                                <a asp-controller="LocationAsset" asp-action="Index" class="">Save Back</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

DNSSoft.Chubb.QuatationTools/DNSSoft.Chubb.QuatationTools/Views/BuildingDetail/_riskModal.cshtml
<div class="modal" id="riskSearchModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <div class="list-group">
          <a href="#" class="list-group-item active"> Code 1 </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>